# Generated by Django 2.2 on 2019-04-28 16:58

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_post_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='lead',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
