# Generated by Django 2.2 on 2019-04-28 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_auto_20190428_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='priority',
            field=models.IntegerField(default=1),
        ),
    ]
