# Generated by Django 2.2 on 2019-04-30 12:00

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('post', '0009_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Author'),
        ),
        migrations.AddField(
            model_name='post',
            name='authorView',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
