# Generated by Django 2.2 on 2019-05-01 20:16

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_auto_20190430_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
