# Generated by Django 2.2 on 2019-05-01 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_author_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
    ]
